// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CartItemInput struct {
	DishID   string `json:"dishId"`
	Quantity int32  `json:"quantity"`
}

type Category struct {
	ID           string  `json:"id"`
	RestaurantID string  `json:"restaurantId"`
	Name         string  `json:"name"`
	Description  *string `json:"description,omitempty"`
	ImageURL     *string `json:"imageUrl,omitempty"`
}

type DeliveryLocationInput struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

// A dish is represented by a Saleor ProductVariant (the `id` field).
type Dish struct {
	ID           string `json:"id"`
	ProductID    string `json:"productId"`
	RestaurantID string `json:"restaurantId"`
	CategoryID   string `json:"categoryId"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	ImageURL     string `json:"imageUrl"`
	Price        *Money `json:"price"`
}

// Telegram Mini App BFF GraphQL API.
//
// This schema is intentionally small and tailored to the frontend flows in `frontend-tma.md`.
type Money struct {
	Amount   float64 `json:"amount"`
	Currency string  `json:"currency"`
}

type Mutation struct {
}

type PlaceOrderInput struct {
	RestaurantID     string                 `json:"restaurantId"`
	Items            []*CartItemInput       `json:"items"`
	DeliveryLocation *DeliveryLocationInput `json:"deliveryLocation,omitempty"`
	GoogleMapsURL    *string                `json:"googleMapsUrl,omitempty"`
	Comment          *string                `json:"comment,omitempty"`
}

type PlaceOrderPayload struct {
	OrderID string `json:"orderId"`
	Status  string `json:"status"`
}

type Query struct {
}

type Restaurant struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	ImageURL    *string  `json:"imageUrl,omitempty"`
	Tags        []string `json:"tags"`
}
